version: "3.8"
services:
  pygeoapi:
    container_name: geoapi
    image: geopython/pygeoapi:latest
    ports:
      - "5000:80"
    volumes:
      - ./pygeocfg.yml:/pygeoapi/local.config.yml
    depends_on:
      - postgres

  postgres:
    container_name: postgres_geo
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - ./hotosm_bdi_waterways.sql.gz:/tests/hotosm_bdi_waterways.sql.gz
    environment:
      - POSTGRES_DB=geo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres